### ISSUE TITLE
Intercepting

### ISSUE THREAD

**Issue by bornasm** [GunHog/MAGNI-Tcomms#3]
Playing the round as a engineer, added the script to all the servers, changed the $Pfq to 1441 so AI doesent get any messages, made myself superuser but still -intercept doesent work, it says its enabled but I cant hear any channels except common. I can talk on all of them but cant listen. Playing on TGstation

**Comment by GunHog** [comment]
It is because the script must be loaded on the department servers as well. Which...means that to get this to work, you have to give yourself superuser on that server, then give the -intercept command. There are two ways to work around this. The first is to manually set the "$Intercept" variable to 1 instead of memory based. The second is to re-route all communications through one server, then enable it.

**Comment by bornasm** [comment]
Thank you for the fast reply! I will test out that tomorrow.
