### ISSUE TITLE
AI and borgs speaking on intercom "say" instead of state

### ISSUE THREAD

**Issue by palpatine213** [GunHog/MAGNI-Tcomms#4]
Title explains it. also had an issue where Declaring (!) and querying(?) don't work, and it just say say and has no punctuation.

Edit: punctuation issue only seems to happen  on common, happens with both intercom and radio

**Comment by GunHog** [comment]
This is normal. The message you hear is a copy of the original message. If you are using the intercoms on 144.1, everything you say is broadcast on common unless you give it a modifier letter or a command. The script was made long before these things, but I have kept it this way to avoid that awful font silicons have. I want to make both all the possible fonts and say() modifiers changeable, but that requires some hairy coding.

It should be possible to include a config to send the original signal in normal speech instead of the copy. I will look into it.

**Comment by GunHog** [comment]
I have a PR up for handling both the fonts and say() verbs. If that gets merged, melding it into my script will be a simple affair.

**Comment by GunHog** [comment]
This should be fixed when the server updates. 1.7 is live now, but will *not* work until the server is updated to latest code.

**Comment by GunHog** [comment]
This is fixed now as well. Tell me if it happens again, though.
